name: lx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
  call_log: ^4.0.0
  liquid_progress_indicator_v2: ^0.5.0
  just_audio: ^0.9.38
  permission_handler: ^11.3.1
  persian_number_utility: ^1.1.4
  speech_to_text: ^6.6.2
  flutter_native_contact_picker: ^0.0.6
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.0
  webview_flutter: ^4.8.0
  flutter_sms_inbox: ^1.0.3
  persian_datetime_picker: ^2.7.0
  jalali_date_time: ^1.3.0
  telephony:
    git:
      url: https://github.com/AliAzizi/fl-telephony.git
      ref: develop
  supabase_flutter: ^2.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/image/homepage/
    - assets/image/adddevice/
    - assets/image/contact/
    - assets/image/relay/
    - assets/image/options2/
    - assets/image/zon/
    - assets/music/
    - assets/music/homepage/
    - assets/music/relay/
    - assets/music/adddevice/
  fonts:
    - family: A
      fonts:
        - asset: assets/IRANSans.ttf
