name: Flutter Build APK

on:
  push:
    branches: [ LuxSecurity ]
  pull_request:
    branches: [ LuxSecurity ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # نسخه Flutter مورد نظر را مشخص کنید
      
      - run: flutter pub get
      
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk